### ISSUE TITLE
how?

### ISSUE THREAD

**Issue by KristerV** [mjmasn/mandrill#1]
do I have to inclide the key value in the options? Please provide a simple getting-started guide.

**Comment by mjmasn** [comment]
There's not much to do to get started. You just need to set an environment variable in your terminal as follows:

```export MANDRILL_API_KEY=yourMandrillKeyHere```

The ```options``` parameter just takes whatever options Mandrill specify in their Node JS library API. Their documentation is at https://mandrillapp.com/api/docs/index.nodejs.html

**Comment by KristerV** [comment]
right, i get it now. thanks

**Comment by madhan5000** [comment]
You can also put it in settings.json file. (put settings.json at root of your app)

    {
        "MANDRILL_API_KEY" : "YOUR KEY"
    }

and invoke it like this 

   > meteor --settings settings.json

A kind request to the authors. I believe it will be very helpful if you put this in the main readme.md will help some one like me.

Thanks !!

**Comment by mjmasn** [comment]
@madhan5000 that method only works for development where you use the `meteor` command. 

In production you run a bundled nodejs application and have to set a ```METEOR_SETTINGS``` environment variable anyway, which if anything is more complicated because you have to create a long JSON string of all your settings rather than setting them individually. 

Even in development, using environment variables is preferable for API keys (and anything remotely sensitive) because it prevents you from checking that sensitive information into version control. If you do use settings.json you should at the very least add it to your .gitignore or equivalent.

**Comment by madhan5000** [comment]
@mjmasn Thanks. Yes it makes sense. I do use mup for production and I put it in mup.json and it is taken care for me.
